export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const TOGGLE_UPDATE_POPUP = 'TOGGLE_UPDATE_POPUP';
export const TOGGLE_UPDATE_DOC_POPUP = 'TOGGLE_UPDATE_DOC_POPUP';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_INDIVIDUAL_COURSE = 'GET_INDIVIDUAL_COURSE';
export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const GET_STUDENTS_ENROLLED = 'GET_STUDENTS_ENROLLED';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const DISCARD_FILE = 'DISCARD_FILE';

export const GET_PERFORMANCE = 'GET_PERFORMANCE';
export const GET_STUDENTS = 'GET_STUDENTS';

export const SET_LOADING = 'SET_LOADING';
